language: node_js

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - gem install jekyll

script:
  - jekyll build --destination public/

after_success:
  - firebase deploy --token={FIREBASE_TOKEN}