language: node_js

branches:
  only:
    - master

before_install:
  - rvm install 2.1
  - rvm use 2.1


install:
  - npm install -g firebase-tools
  - gem install jekyll

script:
  - jekyll build --destination public/

after_success:
  - firebase deploy --token $FIREBASE_TOKEN