defaults:
    meta-description: "Zync | End-to-end encrypted cloud clipboard for dummies!"
    meta-keywords: "zync, cloud, encryption, clipboard"
    title: "Zync"

local:
    assets: "/assets"

remote:
    assets: "//assets.zync.co"

