defaults:
    meta-description: "Zync | End-to-end encrypted cloud clipboard for dummies!"
    meta-keywords: "zync, cloud, encryption, clipboard"
    title: "Zync"

assets:
    local: "/assets"
    remote: "//assets.zync.co"
