defaults:
  title: "Zync"
  description: "Secure clipboard syncing between your devices."
  keywords: "zync, cloud, encryption, clipboard, sync, secure"

sass:
  sass_dir: _sass
  style: compressed

url: "https://zync.co"